import { MaterialIcons } from '@expo/vector-icons';
import { Stack, useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CreatorAccessGate } from '../../../components/CreatorAccessGate';
import { selectionHaptic } from '../../design/haptics';
import type { PluggdTheme } from '../../design/tokens';
import { pluggdFonts } from '../../design/typography';
import { usePluggdTheme } from '../../design/usePluggdTheme';
import { buildEmbeddedStudioRoute } from './studio-data';
import { loadStudioFinancialsWorkspace, type StudioFinancialsWorkspace, type StudioPayout } from './studioFinancialsService';

const dateLabel = (value: string) => new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value));
const statusLabel = (value: string) => value.replaceAll('_', ' ').toUpperCase();
const money = (value: number, currency: 'GBP' | 'USD') => new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(value);

export function StudioFinancialsScreen() {
  const router = useRouter();
  const theme = usePluggdTheme();
  const styles = useMemo(() => createStyles(theme), [theme]);
  const [workspace, setWorkspace] = useState<StudioFinancialsWorkspace | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = async (refresh = false) => {
    refresh ? setRefreshing(true) : setLoading(true);
    setError(null);
    try { setWorkspace(await loadStudioFinancialsWorkspace()); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : String(loadError)); }
    finally { setLoading(false); setRefreshing(false); }
  };
  useEffect(() => { void load(); }, []);

  const pendingPayouts = useMemo(() => workspace?.payouts.filter((item) => ['pending', 'processing'].includes(item.status)).length || 0, [workspace]);

  return <CreatorAccessGate><SafeAreaView style={styles.safe} edges={['top']}><StatusBar style={theme.scheme === 'dark' ? 'light' : 'dark'} /><Stack.Screen options={{ headerShown: false }} />
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back to Creator Studio" style={styles.headerButton} onPress={() => { selectionHaptic(); router.back(); }}><MaterialIcons name="arrow-back" size={24} color={theme.colors.text} /></Pressable><View style={styles.headerCopy}><Text style={styles.headerKicker}>CREATOR STUDIO</Text><Text accessibilityRole="header" style={styles.headerTitle}>Financials</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open advanced Financials workspace" style={styles.headerButton} onPress={() => router.push(buildEmbeddedStudioRoute('/studio/financials', 'Financials', '/studio/financials') as any)}><MaterialIcons name="receipt-long" size={22} color={theme.colors.text} /></Pressable></View>
    {loading && !workspace ? <State loading title="Loading Financials" detail="Checking your balance, activity and payout state…" /> : error || !workspace ? <State title="Financials unavailable" detail={error || 'Your financial summary could not be loaded.'} action="Try again" onAction={() => void load()} /> : <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={theme.colors.accentText} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.hero}><Text style={styles.eyebrow}>AVAILABLE NOW</Text><Text style={styles.balance}>{workspace.balance.availableCredits.toLocaleString()}</Text><Text style={styles.balanceUnit}>PLUGGD credits</Text><View style={styles.summary}><Summary value={workspace.balance.pendingCredits.toLocaleString()} label="PENDING CREDITS" /><Summary value={String(workspace.payouts.length)} label="PAYOUT RECORDS" /><Summary value={String(pendingPayouts)} label="IN PROGRESS" /></View><Pressable accessibilityRole="button" accessibilityLabel="Open Wallet" style={styles.primaryButton} onPress={() => router.push('/wallet' as any)}><MaterialIcons name="account-balance-wallet" size={20} color={theme.colors.onAccent} /><Text style={styles.primaryButtonText}>Open Wallet</Text><MaterialIcons name="arrow-forward" size={20} color={theme.colors.onAccent} /></Pressable></View>

      {workspace.partialErrors.length ? <View style={styles.notice}><MaterialIcons name="info-outline" size={21} color={theme.colors.accentText} /><Text style={styles.noticeText}>Some sources are temporarily unavailable: {workspace.partialErrors.join(', ')}. Pull to refresh; available figures are shown without estimation.</Text></View> : null}

      <SectionHeader kicker="MONEY MOVEMENT" title="Recent activity" />
      <View style={styles.card}>{workspace.activity.length ? workspace.activity.slice(0, 10).map((entry, index) => <View key={entry.id} style={[styles.row, index > 0 && styles.rowBorder]}><View style={styles.rowIcon}><MaterialIcons name={entry.amountCredits >= 0 ? 'south-west' : 'north-east'} size={18} color={entry.amountCredits >= 0 ? theme.colors.success : theme.colors.accentText} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{entry.kind.replaceAll('_', ' ')}</Text><Text style={styles.rowMeta}>{dateLabel(entry.createdAt)}</Text></View><Text style={[styles.rowAmount, entry.amountCredits >= 0 ? styles.positive : styles.negative]}>{entry.amountCredits >= 0 ? '+' : ''}{entry.amountCredits.toLocaleString()}</Text></View>) : <Empty icon="receipt-long" title="No Wallet activity yet" detail="Credit purchases, support, unlocks and eligible earnings will appear here once confirmed." />}</View>

      <SectionHeader kicker="PAYOUT LIFECYCLE" title="Transfers & cash-outs" />
      <View style={styles.payoutStack}>{workspace.payouts.length ? workspace.payouts.map((payout) => <PayoutCard key={`${payout.source}-${payout.id}`} payout={payout} />) : <Empty icon="account-balance" title="No payout records yet" detail="When an eligible payout or cash-out exists, its real processing state will appear here." />}</View>

      <View style={styles.advanced}><View style={styles.advancedIcon}><MaterialIcons name="verified-user" size={24} color={theme.colors.accentText} /></View><View style={styles.advancedCopy}><Text style={styles.advancedTitle}>Protected financial work</Text><Text style={styles.advancedText}>Open secure Financials for tax details, statements, exports, bank details, identity checks and payout settings.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open advanced Financials" style={styles.iconButton} onPress={() => router.push(buildEmbeddedStudioRoute('/studio/financials', 'Financials', '/studio/financials') as any)}><MaterialIcons name="arrow-forward" size={21} color={theme.colors.text} /></Pressable></View>
    </ScrollView>}
  </SafeAreaView></CreatorAccessGate>;
}

function useFinancialStyles() {
  const theme = usePluggdTheme();
  return { theme, styles: useMemo(() => createStyles(theme), [theme]) };
}

function Summary({ value, label }: { value: string; label: string }) { const { styles } = useFinancialStyles(); return <View style={styles.summaryItem}><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>; }
function SectionHeader({ kicker, title }: { kicker: string; title: string }) { const { styles } = useFinancialStyles(); return <View style={styles.sectionHeader}><Text style={styles.sectionKicker}>{kicker}</Text><Text style={styles.sectionTitle}>{title}</Text></View>; }
function PayoutCard({ payout }: { payout: StudioPayout }) { const { styles } = useFinancialStyles(); const active = ['pending', 'processing'].includes(payout.status); return <View style={styles.payoutCard}><View style={styles.payoutTop}><View><Text style={styles.payoutSource}>{payout.source === 'creator_cashout' ? 'CREATOR CASH-OUT' : 'CATALOGUE PAYOUT'}</Text><Text style={styles.payoutAmount}>{money(payout.amount, payout.currency)}</Text></View><View style={[styles.statusBadge, active ? styles.statusActive : styles.statusSettled]}><Text style={styles.statusText}>{statusLabel(payout.status)}</Text></View></View><View style={styles.payoutFacts}><Text style={styles.rowMeta}>Requested {dateLabel(payout.requestedAt)}</Text>{payout.processedAt ? <Text style={styles.rowMeta}>Processed {dateLabel(payout.processedAt)}</Text> : null}{payout.method ? <Text style={styles.rowMeta}>{payout.method.toUpperCase()}</Text> : null}</View>{payout.reference ? <Text style={styles.reference}>Reference {payout.reference}</Text> : null}</View>; }
function Empty({ icon, title, detail }: { icon: string; title: string; detail: string }) { const { theme, styles } = useFinancialStyles(); return <View style={styles.empty}><MaterialIcons name={icon as any} size={34} color={theme.colors.accentText} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{detail}</Text></View>; }
function State({ loading, title, detail, action, onAction }: { loading?: boolean; title: string; detail: string; action?: string; onAction?: () => void }) { const { theme, styles } = useFinancialStyles(); return <View style={styles.state}>{loading ? <ActivityIndicator color={theme.colors.accentText} size="large" /> : <MaterialIcons name="error-outline" size={42} color={theme.colors.danger} />}<Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateText}>{detail}</Text>{action && onAction ? <Pressable accessibilityRole="button" accessibilityLabel={action} style={styles.primaryButton} onPress={onAction}><Text style={styles.primaryButtonText}>{action}</Text></Pressable> : null}</View>; }

function createStyles(theme: PluggdTheme) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.background }, header: { minHeight: 76, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1, borderBottomColor: theme.colors.divider }, headerButton: { width: 46, height: 46, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.controlBorder, backgroundColor: theme.colors.surface, alignItems: 'center', justifyContent: 'center' }, headerCopy: { flex: 1 }, headerKicker: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 9, letterSpacing: 1.6, fontWeight: '900' }, headerTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayExtraBold, fontSize: 27, lineHeight: 31 }, content: { padding: 16, paddingBottom: 64, gap: 15 },
  hero: { borderRadius: 24, borderWidth: 1, borderColor: theme.colors.borderAccent, backgroundColor: theme.colors.accentSoft, padding: 19 }, eyebrow: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 9, letterSpacing: 1.5, fontWeight: '900' }, balance: { color: theme.colors.text, fontFamily: pluggdFonts.displayExtraBold, fontSize: 46, lineHeight: 50, marginTop: 8 }, balanceUnit: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiBold, fontSize: 13 }, summary: { marginTop: 18, paddingTop: 15, borderTopWidth: 1, borderTopColor: theme.colors.divider, flexDirection: 'row' }, summaryItem: { flex: 1 }, summaryValue: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 20 }, summaryLabel: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiBlack, fontSize: 7.5, letterSpacing: 0.8, marginTop: 3 }, primaryButton: { minHeight: 48, marginTop: 18, borderRadius: 16, backgroundColor: theme.colors.accentFill, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, primaryButtonText: { color: theme.colors.onAccent, fontFamily: pluggdFonts.satoshiBlack, fontSize: 12, fontWeight: '900' },
  notice: { borderRadius: 18, borderWidth: 1, borderColor: theme.colors.borderAccent, backgroundColor: theme.colors.accentSoft, padding: 14, flexDirection: 'row', gap: 10 }, noticeText: { flex: 1, color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 11, lineHeight: 17 }, sectionHeader: { marginTop: 7 }, sectionKicker: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 9, letterSpacing: 1.5, fontWeight: '900' }, sectionTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 25, marginTop: 4 }, card: { borderRadius: 20, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, overflow: 'hidden' }, row: { minHeight: 68, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, rowBorder: { borderTopWidth: 1, borderTopColor: theme.colors.divider }, rowIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.colors.surfaceAlt, alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1 }, rowTitle: { color: theme.colors.text, fontFamily: pluggdFonts.satoshiBold, fontSize: 13, textTransform: 'capitalize' }, rowMeta: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 10, marginTop: 2 }, rowAmount: { fontFamily: pluggdFonts.satoshiBlack, fontSize: 13, fontWeight: '900' }, positive: { color: theme.colors.success }, negative: { color: theme.colors.danger },
  payoutStack: { gap: 10 }, payoutCard: { borderRadius: 20, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: 15 }, payoutTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 }, payoutSource: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 8, letterSpacing: 1.2, fontWeight: '900' }, payoutAmount: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 24, marginTop: 4 }, statusBadge: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10 }, statusActive: { backgroundColor: theme.colors.accentSoft }, statusSettled: { backgroundColor: theme.colors.surfacePressed }, statusText: { color: theme.colors.text, fontFamily: pluggdFonts.satoshiBlack, fontSize: 8, letterSpacing: 0.8, fontWeight: '900' }, payoutFacts: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: theme.colors.divider }, reference: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 10, marginTop: 8 },
  advanced: { borderRadius: 20, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: 14, flexDirection: 'row', gap: 11, alignItems: 'center' }, advancedIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: theme.colors.accentSoft, alignItems: 'center', justifyContent: 'center' }, advancedCopy: { flex: 1 }, advancedTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 17 }, advancedText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 10.5, lineHeight: 16, marginTop: 3 }, iconButton: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.controlBorder, backgroundColor: theme.colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' }, empty: { minHeight: 190, borderRadius: 20, padding: 24, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 19, marginTop: 10 }, emptyText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 5 }, state: { flex: 1, padding: 28, alignItems: 'center', justifyContent: 'center' }, stateTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 22, marginTop: 13 }, stateText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 6, marginBottom: 14 },
  });
}
