import { MaterialIcons } from '@expo/vector-icons';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CreatorAccessGate } from '../../../components/CreatorAccessGate';
import { PluggdImage } from '../../components/PluggdImage';
import { impactHaptic, selectionHaptic } from '../../design/haptics';
import type { PluggdTheme } from '../../design/tokens';
import { pluggdFonts } from '../../design/typography';
import { usePluggdTheme } from '../../design/usePluggdTheme';
import { buildEmbeddedStudioRoute } from './studio-data';
import {
  hideStoreProduct,
  loadStudioCommerceWorkspace,
  setMembershipTierActive,
  setSamplePackActive,
  submitStoreProductForReview,
  type StudioCommerceWorkspace,
  type StudioMembershipTier,
  type StudioSamplePack,
  type StudioStoreProduct,
} from './studioCommerceService';

type CommerceTab = 'store' | 'memberships' | 'packs';

function statusLabel(value: string | null | undefined) {
  return (value || 'draft').replaceAll('_', ' ').toUpperCase();
}

function pounds(value: number, isMinor = false) {
  return `£${(isMinor ? value / 100 : value).toFixed(2)}`;
}

export function StudioCommerceScreen() {
  const router = useRouter();
  const theme = usePluggdTheme();
  const styles = useMemo(() => createStyles(theme), [theme]);
  const params = useLocalSearchParams<{ tab?: string }>();
  const initialTab: CommerceTab = params.tab === 'memberships' ? 'memberships' : params.tab === 'packs' ? 'packs' : 'store';
  const [tab, setTab] = useState<CommerceTab>(initialTab);
  const [workspace, setWorkspace] = useState<StudioCommerceWorkspace | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  useEffect(() => { setTab(initialTab); }, [initialTab]);

  const load = async (refresh = false) => {
    refresh ? setRefreshing(true) : setLoading(true);
    setError(null);
    try { setWorkspace(await loadStudioCommerceWorkspace()); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : String(loadError)); }
    finally { setLoading(false); setRefreshing(false); }
  };
  useEffect(() => { void load(); }, []);

  const run = async (key: string, action: () => Promise<void>, success: string) => {
    if (busy) return;
    setBusy(key);
    try {
      await action();
      impactHaptic();
      Alert.alert(success);
      await load(true);
    } catch (actionError) {
      Alert.alert('Commerce action failed', actionError instanceof Error ? actionError.message : String(actionError));
    } finally { setBusy(null); }
  };

  const merchCount = useMemo(() => workspace?.products.filter((product) => /merch|physical/i.test(product.productType)).length || 0, [workspace]);
  const activeCount = (workspace?.products.filter((item) => item.visibility === 'public' && item.isActive).length || 0)
    + (workspace?.memberships.filter((item) => item.status === 'active').length || 0)
    + (workspace?.packs.filter((item) => item.isActive).length || 0);

  return <CreatorAccessGate><SafeAreaView style={styles.safe} edges={['top']}><StatusBar style={theme.scheme === 'dark' ? 'light' : 'dark'} /><Stack.Screen options={{ headerShown: false }} />
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back to Creator Studio" style={styles.headerButton} onPress={() => { selectionHaptic(); router.back(); }}><MaterialIcons name="arrow-back" size={24} color={theme.colors.text} /></Pressable><View style={styles.headerCopy}><Text style={styles.headerKicker}>CREATOR STUDIO</Text><Text accessibilityRole="header" style={styles.headerTitle}>Commerce</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open advanced Store workspace" style={styles.headerButton} onPress={() => router.push(buildEmbeddedStudioRoute('/studio/store', 'Store', '/studio/commerce') as any)}><MaterialIcons name="tune" size={22} color={theme.colors.text} /></Pressable></View>
    {loading && !workspace ? <State loading title="Loading your shop" detail="Checking your products, memberships and Sound Packs…" /> : error || !workspace ? <State title="Commerce unavailable" detail={error || 'Your shop could not be loaded.'} action="Try again" onAction={() => void load()} /> : <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={theme.colors.accentText} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="storefront" size={28} color={theme.colors.accentText} /></View><Text style={styles.heroKicker}>YOUR SHOP</Text><Text style={styles.heroTitle}>Sell without leaving your creator workflow.</Text><Text style={styles.heroBody}>Review what is live, pause availability and submit new work for approval here. Open the specialist workspaces when you need inventory, fulfilment or product builders.</Text><View style={styles.summary}><Summary value={workspace.products.length} label="PRODUCTS" /><Summary value={workspace.memberships.length} label="TIERS" /><Summary value={workspace.packs.length} label="PACKS" /><Summary value={activeCount} label="LIVE" /></View></View>
      <View style={styles.tabs} accessibilityRole="tablist"><Tab label={`Store ${workspace.products.length}`} selected={tab === 'store'} onPress={() => setTab('store')} /><Tab label={`Memberships ${workspace.memberships.length}`} selected={tab === 'memberships'} onPress={() => setTab('memberships')} /><Tab label={`Packs ${workspace.packs.length}`} selected={tab === 'packs'} onPress={() => setTab('packs')} /></View>

      {tab === 'store' ? <View style={styles.stack}><SectionHeader kicker={`${merchCount} MERCH / PHYSICAL`} title="Products & merchandise" action="Advanced Store" onAction={() => router.push(buildEmbeddedStudioRoute('/studio/store', 'Store', '/studio/commerce?tab=store') as any)} />{workspace.products.length ? workspace.products.map((product) => <ProductCard key={product.id} product={product} busy={Boolean(busy)} onSubmit={() => Alert.alert('Send product for review?', 'PLUGGD must approve Store publication. This does not open a fan checkout or make an unapproved product public.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Submit', onPress: () => void run(`submit-${product.id}`, () => submitStoreProductForReview(product.id), 'Product sent for review') }])} onHide={() => Alert.alert('Hide product?', 'This removes the product from public Store surfaces while keeping your draft and files.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Hide', style: 'destructive', onPress: () => void run(`hide-${product.id}`, () => hideStoreProduct(product.id), 'Product hidden') }])} onPublic={() => router.push(`/product/${product.id}` as any)} onAdvanced={() => router.push(buildEmbeddedStudioRoute(/merch|physical/i.test(product.productType) ? '/studio/catalog?tab=merch' : '/studio/store', /merch|physical/i.test(product.productType) ? 'Merchandise' : 'Store', '/studio/commerce?tab=store') as any)} />) : <Empty icon="inventory-2" title="No products yet" detail="Use Advanced Store to create a product draft, merchandise item or physical good." />}</View> : null}

      {tab === 'memberships' ? <View style={styles.stack}><SectionHeader kicker="MEMBERSHIP SETUP" title="Tiers & availability" action="Tier builder" onAction={() => router.push(buildEmbeddedStudioRoute('/studio/memberships/plans', 'Memberships', '/studio/commerce?tab=memberships') as any)} />{workspace.memberships.length ? workspace.memberships.map((tier) => <MembershipCard key={tier.id} tier={tier} busy={Boolean(busy)} onToggle={(active) => void run(`tier-${tier.id}`, () => setMembershipTierActive(tier.id, workspace.profileId, active), active ? 'Membership tier activated' : 'Membership tier paused')} onPublic={() => router.push(`/membership/${workspace.userId}` as any)} onAdvanced={() => router.push(buildEmbeddedStudioRoute('/studio/memberships/plans', 'Memberships', '/studio/commerce?tab=memberships') as any)} />) : <Empty icon="workspace-premium" title="No membership tiers yet" detail="Open the tier builder to configure benefits, billing and access before activation." />}</View> : null}

      {tab === 'packs' ? <View style={styles.stack}><SectionHeader kicker="DIGITAL CATALOGUE" title="Sound packs" action="Pack workspace" onAction={() => router.push(buildEmbeddedStudioRoute('/studio/catalog?tab=sound-packs', 'Sound Packs', '/studio/commerce?tab=packs') as any)} />{workspace.packs.length ? workspace.packs.map((pack) => <PackCard key={pack.id} pack={pack} busy={Boolean(busy)} onToggle={(active) => void run(`pack-${pack.id}`, () => setSamplePackActive(pack.id, active), active ? 'Pack activated' : 'Pack paused')} onPublic={() => router.push(`/sample-pack/${pack.id}` as any)} onAdvanced={() => router.push(buildEmbeddedStudioRoute('/studio/catalog?tab=sound-packs', 'Sound Packs', '/studio/commerce?tab=packs') as any)} />) : <Empty icon="library-music" title="No Sound Packs yet" detail="Open the Pack workspace to upload assets, artwork and licence settings." />}</View> : null}

      <View style={styles.boundary}><MaterialIcons name="verified-user" size={23} color={theme.colors.accentText} /><View style={styles.boundaryCopy}><Text style={styles.boundaryTitle}>Your shop controls stay separate from checkout</Text><Text style={styles.boundaryText}>Managing an item here never starts a purchase. Public previews open only when you choose them, while digital fan purchases keep their App Store checkout.</Text></View></View>
    </ScrollView>}
  </SafeAreaView></CreatorAccessGate>;
}

function useCommerceStyles() {
  const theme = usePluggdTheme();
  return { theme, styles: useMemo(() => createStyles(theme), [theme]) };
}

function Summary({ value, label }: { value: number; label: string }) { const { styles } = useCommerceStyles(); return <View style={styles.summaryItem}><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>; }
function Tab({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const { styles } = useCommerceStyles(); return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} onPress={onPress} style={[styles.tab, selected && styles.tabActive]}><Text style={[styles.tabText, selected && styles.tabTextActive]}>{label}</Text></Pressable>; }
function SectionHeader({ kicker, title, action, onAction }: { kicker: string; title: string; action: string; onAction: () => void }) { const { theme, styles } = useCommerceStyles(); return <View style={styles.sectionHeader}><View style={styles.sectionHeaderCopy}><Text style={styles.sectionKicker}>{kicker}</Text><Text style={styles.sectionTitle}>{title}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={action} style={styles.sectionAction} onPress={onAction}><Text style={styles.sectionActionText}>{action}</Text><MaterialIcons name="arrow-forward" size={16} color={theme.colors.accentText} /></Pressable></View>; }

function ProductCard({ product, busy, onSubmit, onHide, onPublic, onAdvanced }: { product: StudioStoreProduct; busy: boolean; onSubmit: () => void; onHide: () => void; onPublic: () => void; onAdvanced: () => void }) {
  const { theme, styles } = useCommerceStyles();
  const live = product.visibility === 'public' && product.isActive;
  const canSubmit = !['submitted', 'under_review', 'approved'].includes(product.submissionStatus || '') && !live;
  return <View style={styles.card}><View style={styles.media}>{product.imageUrl ? <PluggdImage uri={product.imageUrl} style={StyleSheet.absoluteFill} resizeMode="cover" accessibilityLabel="" /> : <MaterialIcons name={/merch|physical/i.test(product.productType) ? 'checkroom' : 'shopping-bag'} size={40} color={theme.colors.accentText} />}<View style={[styles.badge, live ? styles.badgeLive : styles.badgeDraft]}><Text style={styles.badgeText}>{live ? 'LIVE' : statusLabel(product.submissionStatus || product.moderationStatus)}</Text></View></View><View style={styles.cardBody}><View style={styles.cardTitleRow}><View style={styles.cardTitleCopy}><Text style={styles.cardType}>{statusLabel(product.productType)}</Text><Text style={styles.cardTitle}>{product.title}</Text></View><Text style={styles.price}>{product.currency === 'GBP' ? pounds(product.price) : `${product.currency} ${product.price.toFixed(2)}`}</Text></View>{product.description ? <Text style={styles.cardDescription} numberOfLines={2}>{product.description}</Text> : null}<Text style={styles.cardMeta}>{product.salesCount} sales{product.stockQuantity == null ? '' : ` · ${product.stockQuantity} in stock`} · {statusLabel(product.visibility)}</Text><View style={styles.actions}>{live ? <Pressable accessibilityRole="button" accessibilityLabel={`View public ${product.title}`} disabled={busy} style={styles.action} onPress={onPublic}><MaterialIcons name="visibility" size={18} color={theme.colors.text} /><Text style={styles.actionText}>Public view</Text></Pressable> : null}{canSubmit ? <Pressable accessibilityRole="button" accessibilityLabel={`Submit ${product.title} for Store review`} disabled={busy} style={styles.primaryAction} onPress={onSubmit}><MaterialIcons name="send" size={18} color={theme.colors.onAccent} /><Text style={styles.primaryActionText}>Submit</Text></Pressable> : null}{live ? <Pressable accessibilityRole="button" accessibilityLabel={`Hide ${product.title}`} disabled={busy} style={styles.warnAction} onPress={onHide}><Text style={styles.warnActionText}>Hide</Text></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel={`Open more creator tools for ${product.title}`} disabled={busy} style={styles.iconAction} onPress={onAdvanced}><MaterialIcons name="tune" size={20} color={theme.colors.text} /></Pressable></View></View></View>;
}

function MembershipCard({ tier, busy, onToggle, onPublic, onAdvanced }: { tier: StudioMembershipTier; busy: boolean; onToggle: (active: boolean) => void; onPublic: () => void; onAdvanced: () => void }) {
  const { theme, styles } = useCommerceStyles();
  const active = tier.status === 'active';
  return <View style={styles.simpleCard}><View style={styles.simpleTop}><View style={styles.simpleIcon}><MaterialIcons name="workspace-premium" size={22} color={theme.colors.accentText} /></View><View style={styles.simpleCopy}><Text style={styles.cardType}>{statusLabel(tier.status)} · {statusLabel(tier.syncStatus)}</Text><Text style={styles.cardTitle}>{tier.name}</Text></View><Switch accessibilityLabel={`${tier.name} availability`} style={styles.switch} disabled={busy || tier.status === 'archived'} value={active} onValueChange={onToggle} trackColor={{ false: theme.colors.surfacePressed, true: theme.colors.accentFill }} thumbColor={active ? theme.colors.onAccent : theme.colors.textMuted} /></View><Text style={styles.cardDescription}>{tier.description || 'No tier description yet.'}</Text><View style={styles.tierFacts}><Text style={styles.factValue}>{tier.priceMonthly == null ? 'No monthly price' : `${tier.currency === 'GBP' ? pounds(tier.priceMonthly, true) : `${tier.currency} ${(tier.priceMonthly / 100).toFixed(2)}`} / month`}</Text><Text style={styles.cardMeta}>{tier.currentMembers}{tier.maxMembers == null ? '' : ` / ${tier.maxMembers}`} members</Text></View><View style={styles.actions}>{active ? <Pressable accessibilityRole="button" accessibilityLabel={`Open public ${tier.name} membership`} style={styles.action} onPress={onPublic}><MaterialIcons name="visibility" size={18} color={theme.colors.text} /><Text style={styles.actionText}>Public view</Text></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel={`Configure ${tier.name} membership`} style={styles.action} onPress={onAdvanced}><MaterialIcons name="tune" size={18} color={theme.colors.text} /><Text style={styles.actionText}>Configure</Text></Pressable></View></View>;
}

function PackCard({ pack, busy, onToggle, onPublic, onAdvanced }: { pack: StudioSamplePack; busy: boolean; onToggle: (active: boolean) => void; onPublic: () => void; onAdvanced: () => void }) {
  const { theme, styles } = useCommerceStyles();
  const canActivate = pack.approvalStatus === 'approved';
  return <View style={styles.card}><View style={styles.packRow}><View style={styles.packArt}>{pack.imageUrl ? <PluggdImage uri={pack.imageUrl} style={StyleSheet.absoluteFill} resizeMode="cover" accessibilityLabel="" /> : <MaterialIcons name="library-music" size={30} color={theme.colors.accentText} />}</View><View style={styles.packCopy}><Text style={styles.cardType}>{statusLabel(pack.approvalStatus)}</Text><Text style={styles.cardTitle}>{pack.title}</Text><Text style={styles.cardMeta}>{pack.sampleCount} samples · {pack.downloads} downloads · {pounds(pack.pricePence, true)}</Text></View><Switch accessibilityLabel={`${pack.title} availability`} style={styles.switch} disabled={busy || !canActivate} value={pack.isActive} onValueChange={onToggle} trackColor={{ false: theme.colors.surfacePressed, true: theme.colors.accentFill }} thumbColor={pack.isActive ? theme.colors.onAccent : theme.colors.textMuted} /></View>{!canActivate ? <Text style={styles.reviewNote}>Activation unlocks after PLUGGD approval. You can continue editing assets and licensing in the Pack workspace.</Text> : null}<View style={styles.actions}>{pack.isActive ? <Pressable accessibilityRole="button" accessibilityLabel={`Open public ${pack.title} sample pack`} style={styles.action} onPress={onPublic}><MaterialIcons name="visibility" size={18} color={theme.colors.text} /><Text style={styles.actionText}>Public view</Text></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel={`Manage ${pack.title} sample pack`} style={styles.action} onPress={onAdvanced}><MaterialIcons name="tune" size={18} color={theme.colors.text} /><Text style={styles.actionText}>Manage pack</Text></Pressable></View></View>;
}

function Empty({ icon, title, detail }: { icon: string; title: string; detail: string }) { const { theme, styles } = useCommerceStyles(); return <View style={styles.empty}><MaterialIcons name={icon as any} size={38} color={theme.colors.accentText} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{detail}</Text></View>; }
function State({ loading, title, detail, action, onAction }: { loading?: boolean; title: string; detail: string; action?: string; onAction?: () => void }) { const { theme, styles } = useCommerceStyles(); return <View style={styles.state}>{loading ? <ActivityIndicator color={theme.colors.accentText} size="large" /> : <MaterialIcons name="error-outline" size={42} color={theme.colors.danger} />}<Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateText}>{detail}</Text>{action && onAction ? <Pressable accessibilityRole="button" accessibilityLabel={action} style={styles.primaryAction} onPress={onAction}><Text style={styles.primaryActionText}>{action}</Text></Pressable> : null}</View>; }

function createStyles(theme: PluggdTheme) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.background }, header: { minHeight: 76, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1, borderBottomColor: theme.colors.divider }, headerButton: { width: 46, height: 46, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.controlBorder, backgroundColor: theme.colors.surface, alignItems: 'center', justifyContent: 'center' }, headerCopy: { flex: 1 }, headerKicker: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 9, letterSpacing: 1.6, fontWeight: '900' }, headerTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayExtraBold, fontSize: 27, lineHeight: 31 }, content: { padding: 16, paddingBottom: 60, gap: 16 },
  hero: { borderRadius: 24, borderWidth: 1, borderColor: theme.colors.borderAccent, backgroundColor: theme.colors.accentSoft, padding: 19 }, heroIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: theme.colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' }, heroKicker: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 9, letterSpacing: 1.5, fontWeight: '900', marginTop: 15 }, heroTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayExtraBold, fontSize: 29, lineHeight: 33, marginTop: 6 }, heroBody: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 13, lineHeight: 19, marginTop: 7 }, summary: { marginTop: 18, paddingTop: 15, borderTopWidth: 1, borderTopColor: theme.colors.divider, flexDirection: 'row' }, summaryItem: { flex: 1 }, summaryValue: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 21 }, summaryLabel: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiBlack, fontSize: 8, letterSpacing: 1, marginTop: 3 },
  tabs: { padding: 4, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, flexDirection: 'row' }, tab: { flex: 1, minHeight: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 }, tabActive: { backgroundColor: theme.colors.accentFill }, tabText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiBlack, fontSize: 10, fontWeight: '900' }, tabTextActive: { color: theme.colors.onAccent }, stack: { gap: 13 }, sectionHeader: { minHeight: 64, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 }, sectionHeaderCopy: { flex: 1 }, sectionKicker: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 9, letterSpacing: 1.4, fontWeight: '900' }, sectionTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 24, marginTop: 4 }, sectionAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10 }, sectionActionText: { color: theme.colors.text, fontFamily: pluggdFonts.satoshiBlack, fontSize: 10, fontWeight: '900' },
  card: { borderRadius: 22, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, overflow: 'hidden' }, media: { height: 168, backgroundColor: theme.colors.artworkBase, alignItems: 'center', justifyContent: 'center' }, badge: { position: 'absolute', top: 12, left: 12, borderRadius: 10, paddingHorizontal: 9, paddingVertical: 6 }, badgeLive: { backgroundColor: theme.colors.success }, badgeDraft: { backgroundColor: theme.colors.mediaScrim }, badgeText: { color: theme.colors.mediaText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 8, letterSpacing: 1, fontWeight: '900' }, cardBody: { padding: 15, backgroundColor: theme.colors.surface }, cardTitleRow: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, cardTitleCopy: { flex: 1 }, cardType: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiBlack, fontSize: 8, letterSpacing: 1.2, fontWeight: '900' }, cardTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 20, lineHeight: 24, marginTop: 3 }, price: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 18 }, cardDescription: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 12, lineHeight: 18, marginTop: 8 }, cardMeta: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiBold, fontSize: 10, marginTop: 8 }, actions: { flexDirection: 'row', gap: 8, marginTop: 14, flexWrap: 'wrap' }, action: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.controlBorder, backgroundColor: theme.colors.surfaceRaised, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, actionText: { color: theme.colors.text, fontFamily: pluggdFonts.satoshiBlack, fontSize: 10, fontWeight: '900' }, primaryAction: { minHeight: 44, borderRadius: 12, backgroundColor: theme.colors.accentFill, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, primaryActionText: { color: theme.colors.onAccent, fontFamily: pluggdFonts.satoshiBlack, fontSize: 10, fontWeight: '900' }, warnAction: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.danger, backgroundColor: theme.colors.surface, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' }, warnActionText: { color: theme.colors.danger, fontFamily: pluggdFonts.satoshiBlack, fontSize: 10, fontWeight: '900' }, iconAction: { width: 46, height: 44, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.controlBorder, backgroundColor: theme.colors.surfaceRaised, alignItems: 'center', justifyContent: 'center' },
  simpleCard: { borderRadius: 22, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: 15 }, simpleTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, simpleIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: theme.colors.accentSoft, alignItems: 'center', justifyContent: 'center' }, simpleCopy: { flex: 1 }, switch: { minWidth: 51, minHeight: 44 }, tierFacts: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.divider, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, factValue: { color: theme.colors.text, fontFamily: pluggdFonts.satoshiBlack, fontSize: 12, fontWeight: '900' }, packRow: { padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, packArt: { width: 72, height: 72, borderRadius: 16, backgroundColor: theme.colors.artworkBase, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }, packCopy: { flex: 1 }, reviewNote: { color: theme.colors.accentText, fontFamily: pluggdFonts.satoshiMedium, fontSize: 11, lineHeight: 16, paddingHorizontal: 14, paddingBottom: 2 },
  boundary: { borderRadius: 18, borderWidth: 1, borderColor: theme.colors.borderAccent, backgroundColor: theme.colors.accentSoft, padding: 15, flexDirection: 'row', gap: 12 }, boundaryCopy: { flex: 1 }, boundaryTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 17 }, boundaryText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 11, lineHeight: 17, marginTop: 4 }, empty: { minHeight: 220, borderRadius: 22, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: 26, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 20, marginTop: 11 }, emptyText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 }, state: { flex: 1, padding: 28, alignItems: 'center', justifyContent: 'center' }, stateTitle: { color: theme.colors.text, fontFamily: pluggdFonts.displayBold, fontSize: 22, marginTop: 13 }, stateText: { color: theme.colors.textSecondary, fontFamily: pluggdFonts.satoshiMedium, fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 6, marginBottom: 14 },
  });
}
