-- Fix trigger recursion issue by dropping the problematic trigger
DROP TRIGGER IF EXISTS update_challenges_on_insert ON monthly_challenges;

-- Add sample data without triggering infinite loops
INSERT INTO sample_packs (user_id, title, description, cover_art_url, genre, bpm_range, price, sample_count, tags, download_url, preview_url, is_featured) VALUES
('550e8400-e29b-41d4-a716-446655440000', 'Trap Essentials Vol. 1', 'Hard-hitting trap samples with 808s and snares', '/uploads/392a1a2d-81d9-4106-95aa-a5347c293bc3.png', 'Trap', '140-160 BPM', 29.99, 25, ARRAY['trap', '808', 'dark', 'hard'], 'https://example.com/trap-pack.zip', 'https://example.com/trap-preview.mp3', true),
('550e8400-e29b-41d4-a716-446655440000', 'Lo-Fi Dreams', 'Chill lo-fi samples perfect for relaxing beats', '/uploads/6299467a-f115-4657-9015-ec1f1939e292.png', 'Lo-Fi', '70-90 BPM', 19.99, 30, ARRAY['lofi', 'chill', 'vinyl', 'jazz'], 'https://example.com/lofi-pack.zip', 'https://example.com/lofi-preview.mp3', true),
('550e8400-e29b-41d4-a716-446655440000', 'Future Bass Vibes', 'Euphoric future bass samples and synths', '/uploads/7a7e071e-72b3-4824-aead-f1d0760f6374.png', 'Future Bass', '128-140 BPM', 34.99, 20, ARRAY['future bass', 'edm', 'melodic', 'drops'], 'https://example.com/future-pack.zip', 'https://example.com/future-preview.mp3', false);

-- Add artists
INSERT INTO artists (name, bio, image_url, spotify_url, apple_music_url, youtube_url, soundcloud_url, instagram_url, twitter_url, website_url, is_featured) VALUES
('NOVA BEATS', 'Rising trap producer from Atlanta with over 2M streams across platforms. Known for dark, atmospheric beats.', '/uploads/b19f0151-b9ac-41fa-b010-ed59a5b085ef.png', 'https://open.spotify.com/artist/novabeats', 'https://music.apple.com/artist/novabeats', 'https://youtube.com/@novabeats', 'https://soundcloud.com/novabeats', 'https://instagram.com/novabeats', 'https://twitter.com/novabeats', 'https://novabeats.com', true),
('Luna Waves', 'Lo-fi hip hop artist and producer creating dreamy soundscapes. Featured on major lo-fi playlists.', '/uploads/695d06f7-2a64-4b9c-9cd1-34dd538fc6d9.png', 'https://open.spotify.com/artist/lunawaves', 'https://music.apple.com/artist/lunawaves', 'https://youtube.com/@lunawaves', 'https://soundcloud.com/lunawaves', 'https://instagram.com/lunawaves', 'https://twitter.com/lunawaves', 'https://lunawaves.net', true),
('BASSLINE KING', 'Electronic music producer specializing in future bass and melodic dubstep. 500K+ monthly listeners.', '/uploads/71e3dd35-ce08-4e48-a0c2-a16d8388010c.png', 'https://open.spotify.com/artist/basslineking', 'https://music.apple.com/artist/basslineking', 'https://youtube.com/@basslineking', 'https://soundcloud.com/basslineking', 'https://instagram.com/basslineking', 'https://twitter.com/basslineking', 'https://basslineking.io', true);