-- Messaging inbox RPC helpers and notification utilities
-- Generated by ChatGPT agent to support authenticated inbox flows with pagination

create or replace function public.inbox_list_threads(
  p_limit integer default 20,
  p_cursor timestamptz default null,
  p_search text default null,
  p_thread_id text default null
)
returns table (
  thread_id text,
  social_account_id uuid,
  account_provider text,
  account_label text,
  latest_message jsonb,
  unread_count integer,
  total_messages integer,
  last_message_at timestamptz
)
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;

  return query
  with filtered as (
    select *,
      coalesce(provider_thread_id, provider_message_id) as thread_key
    from public.inbox_messages
    where user_id = v_uid
      and (p_cursor is null or created_at < p_cursor)
      and (
        p_thread_id is null
        or coalesce(provider_thread_id, provider_message_id) = nullif(trim(p_thread_id), '')
      )
      and (
        p_search is null
        or author_name ilike '%' || p_search || '%'
        or author_handle ilike '%' || p_search || '%'
        or content ilike '%' || p_search || '%'
      )
  ),
  latest as (
    select distinct on (thread_key, social_account_id)
      thread_key,
      social_account_id,
      id,
      content,
      author_name,
      author_handle,
      author_avatar_url,
      created_at,
      is_read,
      provider_message_id
    from filtered
    order by thread_key, social_account_id, created_at desc
  ),
  counts as (
    select
      thread_key,
      social_account_id,
      count(*) filter (where is_read = false) as unread_count,
      count(*) as total_messages
    from filtered
    group by thread_key, social_account_id
  )
  select
    latest.thread_key as thread_id,
    latest.social_account_id,
    sa.provider as account_provider,
    coalesce(sa.account_handle, sa.account_name, sa.provider) as account_label,
    jsonb_build_object(
      'id', latest.id,
      'content', latest.content,
      'author_name', latest.author_name,
      'author_handle', latest.author_handle,
      'author_avatar_url', latest.author_avatar_url,
      'created_at', latest.created_at,
      'is_read', latest.is_read,
      'provider_message_id', latest.provider_message_id
    ) as latest_message,
    coalesce(counts.unread_count, 0)::integer,
    coalesce(counts.total_messages, 0)::integer,
    latest.created_at as last_message_at
  from latest
  left join counts
    on counts.thread_key = latest.thread_key
   and counts.social_account_id = latest.social_account_id
  left join public.social_accounts sa on sa.id = latest.social_account_id
  order by latest.created_at desc
  limit greatest(p_limit, 1);
end;
$$;

create or replace function public.inbox_get_thread_messages(
  p_thread_id text,
  p_limit integer default 30,
  p_cursor timestamptz default null
)
returns table (
  id uuid,
  social_account_id uuid,
  provider_message_id text,
  provider_thread_id text,
  content text,
  author_id text,
  author_name text,
  author_handle text,
  author_avatar_url text,
  created_at timestamptz,
  is_read boolean,
  requires_response boolean,
  media_urls text[]
)
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
  v_thread text := nullif(trim(p_thread_id), '');
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;
  if v_thread is null then
    raise exception 'Thread id is required';
  end if;

  return query
  select
    im.id,
    im.social_account_id,
    im.provider_message_id,
    im.provider_thread_id,
    im.content,
    im.author_id,
    im.author_name,
    im.author_handle,
    im.author_avatar_url,
    im.created_at,
    im.is_read,
    im.requires_response,
    im.media_urls
  from public.inbox_messages im
  where im.user_id = v_uid
    and coalesce(im.provider_thread_id, im.provider_message_id) = v_thread
    and (p_cursor is null or im.created_at < p_cursor)
  order by im.created_at desc
  limit greatest(p_limit, 1);
end;
$$;

create or replace function public.inbox_mark_thread_read(
  p_thread_id text
)
returns void
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
  v_thread text := nullif(trim(p_thread_id), '');
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;
  if v_thread is null then
    return;
  end if;

  update public.inbox_messages
     set is_read = true,
         responded_at = coalesce(responded_at, now())
   where user_id = v_uid
     and coalesce(provider_thread_id, provider_message_id) = v_thread
     and is_read = false;
end;
$$;

create or replace function public.inbox_send_message(
  p_thread_id text,
  p_social_account_id uuid,
  p_content text,
  p_author_name text default null,
  p_author_handle text default null
)
returns table (
  id uuid,
  user_id uuid,
  social_account_id uuid,
  provider_message_id text,
  provider_thread_id text,
  message_type text,
  author_id text,
  author_name text,
  author_handle text,
  author_avatar_url text,
  content text,
  media_urls text[],
  parent_post_id uuid,
  parent_provider_post_id text,
  permalink text,
  is_read boolean,
  is_starred boolean,
  is_archived boolean,
  sentiment text,
  requires_response boolean,
  responded_at timestamptz,
  is_hidden boolean,
  is_spam boolean,
  moderation_status text,
  created_at timestamptz,
  received_at timestamptz
)
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
  v_profile record;
  v_thread text := nullif(trim(p_thread_id), '');
  v_message_id text := gen_random_uuid()::text;
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;
  if v_thread is null then
    raise exception 'Thread id is required';
  end if;
  if coalesce(trim(p_content), '') = '' then
    raise exception 'Message content is required';
  end if;

  select full_name, username, avatar_url
    into v_profile
    from public.profiles
   where user_id = v_uid;

  return query
    insert into public.inbox_messages (
      user_id,
      social_account_id,
      provider_message_id,
      provider_thread_id,
      message_type,
      author_id,
      author_name,
      author_handle,
      author_avatar_url,
      content,
      media_urls,
      is_read,
      requires_response,
      responded_at,
      created_at,
      received_at
    )
    values (
      v_uid,
      p_social_account_id,
      v_message_id,
      v_thread,
      'dm',
      v_uid::text,
      coalesce(nullif(p_author_name, ''), v_profile.full_name, v_profile.username, 'You'),
      coalesce(nullif(p_author_handle, ''), v_profile.username),
      v_profile.avatar_url,
      trim(p_content),
      '{}'::text[],
      true,
      false,
      now(),
      now(),
      now()
    )
    returning
      id,
      user_id,
      social_account_id,
      provider_message_id,
      provider_thread_id,
      message_type,
      author_id,
      author_name,
      author_handle,
      author_avatar_url,
      content,
      media_urls,
      parent_post_id,
      parent_provider_post_id,
      permalink,
      is_read,
      is_starred,
      is_archived,
      sentiment,
      requires_response,
      responded_at,
      is_hidden,
      is_spam,
      moderation_status,
      created_at,
      received_at;
end;
$$;

create or replace function public.inbox_unread_count()
returns integer
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
  v_total integer;
begin
  if v_uid is null then
    return 0;
  end if;

  select count(*)
    into v_total
    from public.inbox_messages
   where user_id = v_uid
     and is_read = false;

  return coalesce(v_total, 0);
end;
$$;

create or replace function public.notifications_unread_count()
returns integer
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
  v_total integer;
begin
  if v_uid is null then
    return 0;
  end if;

  select count(*)
    into v_total
    from public.notifications
   where user_id = v_uid
     and read = false
     and dismissed_at is null;

  return coalesce(v_total, 0);
end;
$$;

create or replace function public.notifications_list_recent(
  p_limit integer default 20
)
returns table (
  id uuid,
  type text,
  title text,
  message text,
  data jsonb,
  read boolean,
  created_at timestamptz,
  related_id uuid,
  related_type text
)
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;

  return query
  select
    n.id,
    n.type,
    n.title,
    n.message,
    n.data,
    n.read,
    n.created_at,
    n.related_id,
    n.related_type
  from public.notifications n
  where n.user_id = v_uid
    and n.dismissed_at is null
  order by n.created_at desc
  limit greatest(p_limit, 1);
end;
$$;

create or replace function public.notifications_mark_read(
  p_notification_id uuid
)
returns void
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;

  update public.notifications
     set read = true,
         dismissed_at = now()
   where id = p_notification_id
     and user_id = v_uid;
end;
$$;

create or replace function public.notifications_mark_all_read()
returns void
security definer
set search_path = public
language plpgsql
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Missing auth.uid()';
  end if;

  update public.notifications
     set read = true,
         dismissed_at = now()
   where user_id = v_uid
     and dismissed_at is null;
end;
$$;
