// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkwvqmubhyondemhasjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrd3ZxbXViaHlvbmRlbWhhc2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODIzNDksImV4cCI6MjA2NzE1ODM0OX0.bABRv9v_9mdlfjFs5Txx_VLEX-M9bbhs0LrCbHZIV6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});